blank_issues_enabled: false
contact_links:
  - name: ðŸ’¬ Discussions
    url: https://github.com/thoukydides/matterbridge-dyson-robot/discussions
    about: "If you are seeking support or have questions then please start a discussion here instead of raising an issue."
  - name: ðŸ¤– Ask Dosu
    url: https://github.dosu.com/thoukydides/matterbridge-dyson-robot
    about: "Ask an AI agent any question about this project. (Requires a free https://dosu.dev/ account.)"